### ISSUE TITLE
Can this be made to work for latest JAX release?

### ISSUE THREAD

**Issue by tomsturges** [alonfnt/bayex#25]
During installation I get the error `ERROR: No matching distribution found for jaxlib<0.2.0,>=0.1.69`

My JAX is version 0.4.12

Would it take minor tweaks to get this working for the later JAX releases or it's a huge task?

Thanks

**Comment by alonfnt** [comment]
Thanks for the heads up, I'll take a look this weekend :)

**Comment by tomsturges** [comment]
Thanks :)
