### ISSUE TITLE
Pip install broken

### ISSUE THREAD

**Issue by thomfoster** [alonfnt/bayex#43]
**Describe the bug**
Pip installing the package, then importing with `import bayex` yields the error `ModuleNotFoundError: No module named 'bayex.src'`

**To Reproduce**
Create virtual env with `python3.10.5 -m venv .venv` 
Activate virtual environment with `source .venv/bin/activate`
Install bayes `pip install bayex`
Try to import `import bayex`

```>>> import bayex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thomasfoster/Documents/simplicity_is_all_you_need/.venv/lib/python3.10/site-packages/bayex/__init__.py", line 1, in <module>
    from bayex.src.optimizer import Optimizer, OptimizerState
ModuleNotFoundError: No module named 'bayex.src'```


Cloning the repo and installing with `pip install .` works, but then run into many errors with imports, such as cannot import domain from Bayex

**Comment by pecey** [comment]
The default version on pip points to 0.2.0 which runs into this issue, but `pip install -U bayex==0.2.1rc0` works.

**Comment by alonfnt** [comment]
Thanks @pecey! I've created a new release to fix that, now `pip install bayex` should get the latest version (same as `pip install bayex==0.2.2`)
